import { createClientFromRequest } from 'npm:@base44/sdk@0.8.6';
import { requireProjectAccess } from './utils/requireProjectAccess.js';
import { callLLMSafe } from './_lib/aiPolicy.js';
import { redactPII, redactFinancials } from './_lib/redact.js';

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    const user = await base44.auth.me();
    
    if (!user) {
      return Response.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const { project_id, recipient_email } = await req.json();
    
    if (!project_id) {
      return Response.json({ error: 'project_id required' }, { status: 400 });
    }
    
    await requireProjectAccess(base44, user, project_id);

    // Fetch data for the past week (capped for performance)
    const weekAgo = new Date();
    weekAgo.setDate(weekAgo.getDate() - 7);
    const MAX_ITEMS = 500;

    const [project, tasks, rfis, changeOrders, financials, dailyLogs] = await Promise.all([
      base44.asServiceRole.entities.Project.filter({ id: project_id }).then(p => p[0]),
      base44.asServiceRole.entities.Task.filter({ project_id }, null, MAX_ITEMS),
      base44.asServiceRole.entities.RFI.filter({ project_id }, null, MAX_ITEMS),
      base44.asServiceRole.entities.ChangeOrder.filter({ project_id }, null, MAX_ITEMS),
      base44.asServiceRole.entities.Financial.filter({ project_id }, null, MAX_ITEMS),
      base44.asServiceRole.entities.DailyLog.filter({ project_id }, null, 100)
    ]);

    // Filter for recent activity
    const recentTasks = tasks.filter(t => new Date(t.updated_date) > weekAgo);
    const recentRFIs = rfis.filter(r => new Date(r.created_date) > weekAgo);
    const recentCOs = changeOrders.filter(c => new Date(c.created_date) > weekAgo);
    const recentLogs = dailyLogs.filter(l => new Date(l.log_date) > weekAgo);

    const completedTasks = tasks.filter(t => t.status === 'completed').length;
    const totalTasks = tasks.length;
    const progress = totalTasks > 0 ? (completedTasks / totalTasks) * 100 : 0;

    const actualCost = financials.reduce((sum, f) => sum + (f.actual_amount || 0), 0);
    const budget = project?.contract_value || 0;
    const budgetUsed = budget > 0 ? (actualCost / budget) * 100 : 0;

    const prompt = `Generate a professional weekly project digest for this structural steel project.

STATUS: ${project?.status}
PHASE: ${project?.phase}

PROGRESS THIS WEEK:
- Tasks completed: ${recentTasks.filter(t => t.status === 'completed').length}
- Tasks started: ${recentTasks.filter(t => t.status === 'in_progress').length}
- Overall progress: ${progress.toFixed(1)}%

FINANCIAL STATUS (RATIOS):
- Budget used: ${budgetUsed.toFixed(1)}%

RFIS & COS:
- New RFIs this week: ${recentRFIs.length}
- New change orders: ${recentCOs.length}
- Pending RFI responses: ${rfis.filter(r => ['pending', 'submitted'].includes(r.status)).length}

FIELD ACTIVITY:
- Daily logs submitted: ${recentLogs.length}
- Safety incidents: ${recentLogs.filter(l => l.safety_incidents).length}
- Weather delays: ${recentLogs.filter(l => l.delays).length}

Generate an executive summary in professional tone covering:
1. Week highlights & accomplishments
2. Current status & progress
3. Risks & concerns (if any)
4. Next week's focus areas
5. Action items requiring attention

Format as an email-ready summary. NO PII, NO dollar amounts.`;

    const response = await callLLMSafe(base44, {
      prompt,
      payload: null,
      project_id,
      response_json_schema: {
        type: "object",
        properties: {
          subject: { type: "string" },
          summary: { type: "string" },
          highlights: { type: "array", items: { type: "string" } },
          concerns: { type: "array", items: { type: "string" } },
          next_week_focus: { type: "array", items: { type: "string" } },
          action_items: { type: "array", items: { type: "string" } },
          metrics: {
            type: "object",
            properties: {
              progress_percent: { type: "number" },
              budget_used_percent: { type: "number" },
              tasks_completed_this_week: { type: "number" },
              open_rfis: { type: "number" }
            }
          }
        }
      }
    });

    // Optionally send email
    if (recipient_email) {
      await base44.integrations.Core.SendEmail({
        to: recipient_email,
        subject: response.subject,
        body: `
<h2>${response.subject}</h2>

<h3>Executive Summary</h3>
<p>${response.summary}</p>

<h3>Week Highlights</h3>
<ul>
${response.highlights.map(h => `<li>${h}</li>`).join('\n')}
</ul>

${response.concerns.length > 0 ? `
<h3>Concerns & Risks</h3>
<ul>
${response.concerns.map(c => `<li>${c}</li>`).join('\n')}
</ul>
` : ''}

<h3>Next Week Focus</h3>
<ul>
${response.next_week_focus.map(f => `<li>${f}</li>`).join('\n')}
</ul>

<h3>Action Items</h3>
<ul>
${response.action_items.map(a => `<li>${a}</li>`).join('\n')}
</ul>

<hr>
<p><small>Generated by SteelBuild Pro on ${new Date().toLocaleDateString()}</small></p>
        `
      });
    }

    return Response.json(response);
  } catch (error) {
    return Response.json({ error: error.message }, { status: 500 });
  }
});